format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
$line_break\
$character\
$cmd_duration"""

[character]
success_symbol = "[â•°â”€Î»](red)"
error_symbol = " [Ã—](purple)"
vimcmd_symbol = " [â®](green)"

[username]
show_always = true
style_user = "red"
style_root = "red"
format = '[â•­â”€$user]($style)@'
disabled = false

[hostname]
format = "[$hostname]($style)"
style = "bold dimmed red"
trim_at = "-"
ssh_only = false
disabled = false

[os]
#style = "bg:#a3aed2 fg:#090c0c"
#format = '[ $symbol]($style)'
disabled = false

[directory]
style = "italic purple"
format = " [$path]($style)"
truncation_length = 5
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
style = "italic cyan"
symbol = "ğŸ£ "
format = " [$symbol$branch]($style)"

[git_commit]
commit_hash_length = 8
style = "italic cyan"

[git_state]
format = ' [\($state($progress_current of $progress_total)\)]($style) '

[git_status]
style = "italic cyan"
format = ' [($all_status$ahead_behind)]($style)'
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = " ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"

[nodejs]
style = "italic cyan"

[golang]
style = "italic cyan"

[php]
style = "italic cyan"

[time]
disabled = false
time_format = "ğŸ•™ %R" # Hour:Minute Format
style = "italic green"
format = ' [$time]($style)'

[cmd_duration]
format = "[$duration]($style) "
style = "purple"
