format = """
[â•­ ](white)\
[â–‘â–’â–“](fg:blue)\
$username\
[â–‘â–’â–“](bg:blue fg:purple)\
$directory\
[â–‘â–’â–“](bg:purple fg:cyan)\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nodejs\
$rust\
$golang\
$php\
[â–‘â–’â–“](bg:cyan fg:green)\
$time\
[â–“â–’â–‘ ](fg:green)\
$line_break\
[â•° ](white)\
$os\
$cmd_duration\
$character"""

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

[username]
show_always = true
style_user = "italic bg:blue"
style_root = "italic dimmed bg:blue"
format = '[ $user ]($style)'
disabled = false

[os]
#style = "bg:#a3aed2 fg:#090c0c"
#format = '[ $symbol]($style)'
disabled = false

[directory]
style = "italic bg:purple"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
style = "italic bg:cyan"
symbol = "ğŸ£ "
format = "[ $symbol$branch ]($style)"

[git_commit]
commit_hash_length = 8
style = "italic bg:cyan"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
style = "italic bg:cyan"
format = '[($all_status$ahead_behind )]($style)'
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = " ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"

[nodejs]
style = "italic bg:cyan"

[golang]
style = "italic bg:cyan"

[php]
style = "italic bg:cyan"

[time]
disabled = false
time_format = "ğŸ•™ %R" # Hour:Minute Format
style = "italic bg:green"
format = '[ $time ]($style)'

[cmd_duration]
format = "[$duration]($style) "
style = "purple"
